### ISSUE TITLE
Private Package Option

### ISSUE THREAD

**Issue by valeryan** [composer/spdx-licenses#23]
Is there a way to set a package licensing as "private" or "all rights reserved".  We use this on a project that has a mix of public and private packages to validate the licenses but on the private packages, we would like to be able to specify that the package is unlicensed and cannot be distributed. 

NPM as added a similar option to their system and it would be really nice here. 

Thanks

**Comment by alcohol** [comment]
Not in this library. But Composer supports `proprietary` as a value for the license field. It will consider the field filled, but it will not be validated against the Spdx specification.

**Comment by alcohol** [comment]
BTW, this is also documented: https://getcomposer.org/doc/04-schema.md#license

**Comment by valeryan** [comment]
Thanks, that will help a bunch. I did not realize this package was documented on the composer site.

**Comment by alcohol** [comment]
This package was originally part of Composer core. We extracted it because it serves a very specific purpose and it has a high re-usability factor. But it is still part of Composer core in a way.
