### ISSUE TITLE
Please, make test available in github archive

### ISSUE THREAD

**Issue by remicollet** [composer/spdx-licenses#5]
Please consider removing tests from .gitattributes.
This make downstream CI easier.
(really small)

See http://blog.remirepo.net/post/2014/08/12/Koschei-continuous-integration-of-PHP-stack-in-Fedora

**Comment by alcohol** [comment]
I'm not sure I understand the rational behind this? The aim with the export-ignore is to make the dist version as small as possible. If you want to run the test suite, you should just do an install from source.

**Comment by remicollet** [comment]
Why PHP provides its test suite ?
Why all projects (outside composer world) provide their test suite ?
Why PHP projects should be different ?

**Comment by alcohol** [comment]
That does not answer my question.

Also, this project does provide a test suite. But the test suite does not belong in a production release (such as dist). When you install PHP on your server, you don't get the PHP test suite, you get the pre-built binary, a production release. The same applies here.

**Comment by remicollet** [comment]
So sorry, we have a different vision of upstream / downstream things.

I can live with that... (I already does for some other projects).
I just think that test, doc, license, should be part of the archive, as they are useful for users (and especially for downstream distribution).

I understand the goal of "minimal" size... not the way to achieve it.

**Comment by alcohol** [comment]
But that is exactly why there are multiple ways to install a dependency. If you specify `--prefer-source` you will get everything. If you specify `--prefer-dist`, you will get a smaller release, more suitable for production.

**Comment by remicollet** [comment]
Please, don't forget that NOT everyone is using composer ;)
And downstream we are still using archive tarball.

**Comment by alcohol** [comment]
Well I'm sorry, but it's 2015... :-)

But in that case, if you want the test suite, `git clone` is your friend.

**Comment by alcohol** [comment]
To be fair though, it's just one file, so if it would make everyone happy... I guess we can just include it.

/cc @Seldaek any thoughts on this?

**Comment by Seldaek** [comment]
My thought is I kinda don't mind either way. It makes a lot of people happy
to trim down the zip so I'm ok doing it. It shouldn't take much away from
others since a clone still ships everything.
