### ISSUE TITLE
Why dep on justinrainbow/json-schema ?

### ISSUE THREAD

**Issue by remicollet** [composer/spdx-licenses#6]
I don't see any usage of JsonSchema namespace in the code.

See "phpcompatinfo ananyser:run src" report

    Classes Analysis
    Class                             Matches REF  EXT min/Max PHP min/Max PHP all 
    Composer\Spdx\SpdxLicenses        2       user             5.3.0               
    Composer\Spdx\SpdxLicensesUpdater         user             5.3.0               
    DOMDocument                       2       dom  5.0.0       5.0.0               
    DOMXPath                          2       dom  5.0.0       5.0.0               
    InvalidArgumentException          2       spl  5.1.0       5.1.0               
    RuntimeException                  1       spl  5.1.0       5.1.0               
    self                              2       Core 5.0.0       5.0.0               
    Total [7]                                                  5.3.0

**Comment by alcohol** [comment]
That's a very valid question. That shouldn't be there. My bad :-(. Thank you for pointing out this mistake.
